# Generated by Django 3.2 on 2023-02-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Namn')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Adress')),
                ('constructor', models.CharField(blank=True, max_length=254, null=True, verbose_name='Byggare')),
                ('contact_person', models.CharField(blank=True, max_length=254, null=True, verbose_name='Kontaktperson')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Anteckningar')),
                ('drawing', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ladda upp ritning')),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekt',
            },
        ),
    ]
