# Generated by Django 3.2 on 2023-02-07 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Ladda upp ritning'),
        ),
        migrations.CreateModel(
            name='ControlChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_type', models.CharField(choices=[('1-flyg', '1-flyg'), ('2-flyg', '2-flyg')], max_length=6, verbose_name='Dörrtyp')),
                ('position_id', models.CharField(max_length=14, verbose_name='Dörrposition/ID')),
                ('done_by', models.CharField(max_length=54, verbose_name='Utfört av')),
                ('date', models.DateField()),
                ('doorframe', models.BooleanField(verbose_name='Dörrkarm')),
                ('door_leaves', models.BooleanField(verbose_name='Dörrblad')),
                ('threshold', models.BooleanField(verbose_name='Tröskel')),
                ('hinge', models.BooleanField(verbose_name='Gångjärn')),
                ('lock_chest', models.BooleanField(verbose_name='Låskista')),
                ('end_plate', models.BooleanField(verbose_name='Slutbleck')),
                ('edge_rule', models.BooleanField(verbose_name='Kantregel')),
                ('door_coordinator', models.BooleanField(verbose_name='Dörrkoordinator')),
                ('door_environment_clean', models.BooleanField(verbose_name='Dörrmiljö rengjord')),
                ('opener_attached_to_the_wall', models.BooleanField(verbose_name='Öppnare riktigt fäst till vägg/parti')),
                ('arm_system_attached', models.BooleanField(verbose_name='Armsystem riktigt fäst till öppnare/dörr')),
                ('arm_system_adjusted', models.BooleanField(verbose_name='Armsystem riktigt justerat')),
                ('cloosing_speed_adjusted1', models.BooleanField(verbose_name='Stängningshastighet riktigt justerat 1-flyg')),
                ('closing_speed_adjusted2', models.BooleanField(verbose_name='Stängningshastighet riktigt justerat 2-flyg')),
                ('opening_speed_adjusted1', models.BooleanField(verbose_name='Öppningshastighet riktigt justerat 1-flyg')),
                ('opening_speed_adjusted2', models.BooleanField(verbose_name='Öppningshastighet riktigt justerat 2-flyg')),
                ('opening_coordination', models.BooleanField(verbose_name='Öppningskoordinering riktigt inställt 2-flyg')),
                ('safety_sensor_tested', models.BooleanField(verbose_name='Säkerhetssensor, justerad och testad')),
                ('impulse_sensor_adjusted', models.BooleanField(verbose_name='Impulsgivare (radar) riktigt monterat och justerat')),
                ('control_signals_tested', models.BooleanField(verbose_name='Styrsignaler från passersystem testat')),
                ('fire_signals_tested', models.BooleanField(verbose_name='Styrsignaler från brandlarm testat')),
                ('notes', models.TextField(help_text='Ange anmärkningar till fälten som inte är ibockade ovan', max_length=1000, verbose_name='Anmärkningar')),
                ('signature', jsignature.fields.JSignatureField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_automation_forms.object')),
            ],
            options={
                'verbose_name': 'Kontrollschema',
                'verbose_name_plural': 'Kontrollscheman',
            },
        ),
    ]
