# Generated by Django 3.2 on 2023-02-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0002_auto_20230207_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlchart',
            name='arm_system_adjusted',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Armsystem riktigt justerat'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='arm_system_attached',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Armsystem riktigt fäst till öppnare/dörr'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='cloosing_speed_adjusted1',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Stängningshastighet riktigt justerat 1-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='closing_speed_adjusted2',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Stängningshastighet riktigt justerat 2-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='control_signals_tested',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Styrsignaler från passersystem testat'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='door_coordinator',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Dörrkoordinator'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='door_environment_clean',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Dörrmiljö rengjord'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='door_leaves',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Dörrblad'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='doorframe',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Dörrkarm'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='edge_rule',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Kantregel'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='end_plate',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Slutbleck'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='fire_signals_tested',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Styrsignaler från brandlarm testat'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='hinge',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Gångjärn'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='impulse_sensor_adjusted',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Impulsgivare (radar) riktigt monterat och justerat'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='lock_chest',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Låskista'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='notes',
            field=models.TextField(help_text='Ange anmärkningar. Börja med siffran följt av notering. Ny anmärkning på ny rad.', max_length=1000, verbose_name='Anmärkningar'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='opener_attached_to_the_wall',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Öppnare riktigt fäst till vägg/parti'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='opening_coordination',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Öppningskoordinering riktigt inställt 2-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='opening_speed_adjusted1',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Öppningshastighet riktigt justerat 1-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='opening_speed_adjusted2',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Öppningshastighet riktigt justerat 2-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='safety_sensor_tested',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Säkerhetssensor, justerad och testad'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='threshold',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='Tröskel'),
        ),
    ]
