# Generated by Django 3.2 on 2023-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0003_auto_20230209_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlchart',
            name='arm_system_adjusted',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='12. Armsystem riktigt justerat'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='arm_system_attached',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='11. Armsystem riktigt fäst till öppnare/dörr'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='cloosing_speed_adjusted1',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='13. Stängningshastighet riktigt justerat 1-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='closing_speed_adjusted2',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='14. Stängningshastighet riktigt justerat 2-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='control_signals_tested',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='20. Styrsignaler från passersystem testat'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='door_coordinator',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='8. Dörrkoordinator'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='door_environment_clean',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='9. Dörrmiljö rengjord'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='door_leaves',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='2. Dörrblad'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='doorframe',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='1. Dörrkarm'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='edge_rule',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='7. Kantregel'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='end_plate',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='6. Slutbleck'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='fire_signals_tested',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='21. Styrsignaler från brandlarm testat'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='hinge',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='4. Gångjärn'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='impulse_sensor_adjusted',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='19. Impulsgivare (radar) riktigt monterat och justerat'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='lock_chest',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='5. Låskista'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='opener_attached_to_the_wall',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='10. Öppnare riktigt fäst till vägg/parti'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='opening_coordination',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='17. Öppningskoordinering riktigt inställt 2-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='opening_speed_adjusted1',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='15. Öppningshastighet riktigt justerat 1-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='opening_speed_adjusted2',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='16. Öppningshastighet riktigt justerat 2-flyg'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='safety_sensor_tested',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='18. Säkerhetssensor, justerad och testad'),
        ),
        migrations.AlterField(
            model_name='controlchart',
            name='threshold',
            field=models.CharField(choices=[('OK', 'OK'), ('ANM', 'Anm.'), ('N/A', 'Ej aktuell')], max_length=6, verbose_name='3. Tröskel'),
        ),
    ]
