# Generated by Django 3.2 on 2023-02-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0005_choice_riskanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlchart',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_automation_forms.riskanalysis'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='A',
            field=models.ManyToManyField(related_name='a_choices', to='door_automation_forms.Choice', verbose_name='A. Klämrisk*'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='B',
            field=models.ManyToManyField(related_name='b_choices', to='door_automation_forms.Choice', verbose_name='B. Klämrisk*'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='C',
            field=models.ManyToManyField(related_name='c_choices', to='door_automation_forms.Choice', verbose_name='C. Klämrisk'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='D',
            field=models.ManyToManyField(related_name='d_choices', to='door_automation_forms.Choice', verbose_name='D. Klämrisk'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='E',
            field=models.ManyToManyField(related_name='e_choices', to='door_automation_forms.Choice', verbose_name='E. Klämrisk'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='risk',
            field=models.CharField(choices=[('LOW', 'Låg risk'), ('HIGH', 'Hög risk')], help_text='Hög risk* Om användarna till stor del är äldre,\n        funktionshindrade personer eller barn kan all kontakt mellan dörrbladen/dörrkonstruktionen och användaren betraktas som riskfylld.\n        Gäller alla automatiska dörrar som inte uppfyller Low Energy-nivån (begränsningar i hastighet, vikt och massa i rörelse).\n        Låg risk** Om användargruppen inte passar in i beskrivningen ovan och dörrautomatiken Low Energy används.', max_length=4, verbose_name='Risknivå'),
        ),
    ]
