# Generated by Django 3.2 on 2023-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0006_auto_20230215_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlchart',
            name='position_id',
            field=models.CharField(max_length=14, verbose_name='Dörrposition/ID'),
        ),
    ]
