# Generated by Django 3.2 on 2023-02-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0007_alter_controlchart_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlchart',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_automation_forms.riskanalysis', verbose_name='Dörr ID'),
        ),
    ]
