# Generated by Django 3.2 on 2023-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0010_alter_choice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskanalysis',
            name='A',
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='A',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=50, null=True, verbose_name='A. Klämrisk*'),
        ),
        migrations.RemoveField(
            model_name='riskanalysis',
            name='B',
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='B',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=50, null=True, verbose_name='B. Klämrisk*'),
        ),
        migrations.RemoveField(
            model_name='riskanalysis',
            name='C',
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='C',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=50, null=True, verbose_name='C. Klämrisk'),
        ),
        migrations.RemoveField(
            model_name='riskanalysis',
            name='D',
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='D',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=50, null=True, verbose_name='D. Klämrisk'),
        ),
        migrations.RemoveField(
            model_name='riskanalysis',
            name='E',
        ),
        migrations.AddField(
            model_name='riskanalysis',
            name='E',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=50, null=True, verbose_name='E. Klämrisk'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
