# Generated by Django 3.2 on 2023-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0011_auto_20230215_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskanalysis',
            name='A',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=17, null=True, verbose_name='A. Klämrisk*'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='B',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=17, null=True, verbose_name='B. Klämrisk*'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='C',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=17, null=True, verbose_name='C. Klämrisk'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='D',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=17, null=True, verbose_name='D. Klämrisk'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='E',
            field=models.CharField(blank=True, choices=[('protective_covers', 'Skyddskåpor eller dylikt'), ('barriers', 'Barriärer'), ('obstacles', 'Hinder'), ('safety_sensors', 'Säkerhetssensorer'), ('low_energy_level', 'Low Energy-nivå')], max_length=17, null=True, verbose_name='E. Klämrisk'),
        ),
        migrations.AlterField(
            model_name='riskanalysis',
            name='door_id',
            field=models.CharField(max_length=50, verbose_name='Dörr-ID/platsbeskrivning'),
        ),
    ]
