# Generated by Django 3.2 on 2023-02-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0014_installationdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationdescription',
            name='electromechanical_lock_external_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='installationdescription',
            name='electromechanical_lock_internal_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='installationdescription',
            name='impulse_generator_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='installationdescription',
            name='mechanical_micro_switch_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='installationdescription',
            name='program_selector_external_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='installationdescription',
            name='program_selector_internal_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='installationdescription',
            name='sensors_notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kommentar'),
        ),
    ]
