# Generated by Django 3.2 on 2023-02-27 10:06

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('door_automation_forms', '0015_auto_20230221_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_year', models.CharField(max_length=4, verbose_name='År')),
                ('periodic_control', models.BooleanField(verbose_name='Periodisk kontroll och underhåll, s. 5-7 (A-C)')),
                ('periodic_control_notes', models.CharField(max_length=200, verbose_name='Rapport/fel/ska utföras')),
                ('repair_ordered', models.BooleanField(verbose_name='Beställd reparation')),
                ('repair_ordered_notes', models.CharField(max_length=200, verbose_name='Rapport/fel/ska utföras')),
                ('installation_changed', models.BooleanField(verbose_name='Ändring av installation')),
                ('installation_changed_notes', models.CharField(max_length=200, verbose_name='Rapport/fel/ska utföras')),
                ('other', models.BooleanField(verbose_name='Annat')),
                ('other_notes', models.CharField(max_length=200, verbose_name='Rapport/fel/ska utföras')),
                ('company', models.CharField(max_length=54, verbose_name='Utförande företag')),
                ('technician', models.CharField(max_length=54, verbose_name='Tekniker')),
                ('date', models.DateField()),
                ('signature', jsignature.fields.JSignatureField()),
                ('door_automatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door_automation_forms.installationdescription')),
            ],
            options={
                'verbose_name': 'Serviceprotokoll',
                'verbose_name_plural': 'Serviceprotokoll',
            },
        ),
    ]
